name: CI Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, xml, ctype, iconv, json, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install PHP Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM Dependencies & Build Assets
        run: |
          echo "prefix=~/.npm" >> ~/.npmrc
          npm ci
          npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Execute Tests (Pest Extreme Coverage)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
          APP_KEY: base64:tExTeStKeYfOrBaNkLeVeLaUtHeNtIcAtIoN123=
        run: ./vendor/bin/pest --coverage --min=100
